"""Parity golden tests: the byte-identical contract for the backbone rewrite.

Each fixture's parsed output is pinned in ``tests/goldens/<fixture>.parity.json``
(generated by ``scripts/make_goldens.py parity`` against the pre-rewrite code).
These tests assert bitwise equality — no tolerances, ever. Floats survive a
JSON round-trip exactly, so comparisons run on parsed objects, never on
serialized text.

Missing goldens or fixtures FAIL, they never skip: a silently skipped parity
suite is indistinguishable from a green one.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import numpy as np
import pyarrow as pa
import pytest

from pyngb import read_ngb, read_ngb_metadata

FIXTURE_DIR = Path(__file__).parent / "test_files"
GOLDEN_DIR = Path(__file__).parent / "goldens"

# Frozen list, deliberately duplicated from scripts/make_goldens.py: the test
# suite must not depend on the generator, and a fixture vanishing from disk
# must fail loudly here.
FIXTURES = (
    "DF_FILED_STA_21O2_10K_220222_R1.ngb-ss3",
    "Douglas_Fir_STA_10K_250730_R13.ngb-ss3",
    "Douglas_Fir_STA_Baseline_10K_250730_R13.ngb-bs3",
    "Douglas_Fir_STA_Baseline_10K_250813_R15.ngb-bs3",
    "Red_Oak_STA_10K_250731_R7.ngb-ss3",
    "RO_FILED_STA_N2_10K_250129_R29.ngb-ss3",
)


def _blake2b(path: Path) -> str:
    digest = hashlib.blake2b()
    with path.open("rb") as f:
        while chunk := f.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def _canonical_bytes(table: pa.Table, name: str) -> bytes:
    """Canonical column representation: little-endian float64 bytes."""
    return np.asarray(table[name].to_numpy(), dtype="<f8").tobytes()


def _stats(table: pa.Table, name: str) -> dict[str, Any]:
    arr = np.asarray(table[name].to_numpy(), dtype="<f8")
    return {
        "first": float(arr[0]) if arr.size else None,
        "last": float(arr[-1]) if arr.size else None,
        "min": float(arr.min()) if arr.size else None,
        "max": float(arr.max()) if arr.size else None,
        "null_count": table[name].null_count,
    }


def _load_golden(fixture: str) -> dict[str, Any]:
    golden_path = GOLDEN_DIR / f"{fixture}.parity.json"
    if not golden_path.is_file():
        pytest.fail(
            f"Parity golden missing: {golden_path}. "
            "Goldens are committed; regenerate only with justification via "
            "`uv run python scripts/make_goldens.py parity`."
        )
    with golden_path.open(encoding="utf-8") as f:
        return json.load(f)


def _parse_metadata_only(path: Path) -> dict[str, Any]:
    """The metadata-only parse path under test.

    This helper is the single seam for that path: the assertions in
    ``test_metadata_only_parity`` are permanent, only this body changes when
    the implementation moves.
    """
    return dict(read_ngb_metadata(path))


@pytest.mark.parametrize("fixture", FIXTURES)
def test_fixture_present(fixture: str) -> None:
    """Meta-test: every fixture exists on disk.

    Guards the silent-skip bug class: fixture-dependent tests elsewhere skip
    or no-op when the fixture directory is empty, so an accidental
    move/rename could green the suite while testing nothing.
    """
    assert (FIXTURE_DIR / fixture).is_file(), f"Fixture missing: {fixture}"


@pytest.mark.parametrize("fixture", FIXTURES)
def test_fixture_identity(fixture: str) -> None:
    """The fixture file itself is bit-identical to when its golden was made."""
    golden = _load_golden(fixture)
    assert _blake2b(FIXTURE_DIR / fixture) == golden["fixture_blake2b"], (
        f"{fixture} has changed on disk; parity comparisons against its "
        "golden are meaningless"
    )


@pytest.mark.parametrize("fixture", FIXTURES)
def test_full_parse_parity(fixture: str) -> None:
    """read_ngb(return_metadata=True) matches the pinned golden exactly."""
    golden = _load_golden(fixture)
    metadata, table = read_ngb(str(FIXTURE_DIR / fixture), return_metadata=True)

    assert metadata == golden["metadata"]
    assert table.column_names == golden["columns"]
    assert {
        name: str(table.schema.field(name).type) for name in table.column_names
    } == golden["column_dtypes"]
    assert table.num_rows == golden["num_rows"]

    for name in golden["columns"]:
        actual = hashlib.sha256(_canonical_bytes(table, name)).hexdigest()
        assert actual == golden["column_sha256"][name], (
            f"{fixture}: column {name!r} bytes diverge from golden.\n"
            f"  golden stats: {golden['column_stats'][name]}\n"
            f"  actual stats: {_stats(table, name)}"
        )


@pytest.mark.parametrize("fixture", FIXTURES)
def test_metadata_only_parity(fixture: str) -> None:
    """The metadata-only path matches the golden (sans file_hash).

    file_hash is added by ``read_ngb`` on top of the parse, not by the
    metadata extraction itself, so the metadata-only path is pinned against
    the golden metadata without it.
    """
    golden = _load_golden(fixture)
    expected = {k: v for k, v in golden["metadata"].items() if k != "file_hash"}
    assert _parse_metadata_only(FIXTURE_DIR / fixture) == expected
